### ISSUE TITLE
Loading errors encountered

### ISSUE THREAD

**Issue by stolenvw** [Lothrazar/FLib#1]
Minecraft Version: 1.20.1

Forge Version: 47.1.33

Mod Version: 0.0.8

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

```
[18Jul2023 16:14:02.414] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Mod §eflib§r requires §6forge§r §obetween 47 and 47.1.3 (inclusive)§r
§7Currently, §6forge§r§7 is §o47.1.33
]
```

i also tried forge Versions 47.1.29 and 47.1.30

This error does not happen with version 0.0.7 of FLib

**Comment by jstansel** [comment]
The message says that Forge 47.1.3 is the highest version supported.

**Comment by Xplodin** [comment]
would love to see the mod on a forge higher than .3

I cant use .3 else it breaks tons of mods

**Comment by stolenvw** [comment]
> would love to see the mod on a forge higher than .3
> 
> I cant use .3 else it breaks tons of mods

I had an other mod that updated yesterday lock down to .3 also, they lest put it in there change log letting you know

**Comment by Lothrazar** [comment]
oops! i just added v0.0.9 without that restriction, any forge is fine now https://www.curseforge.com/minecraft/mc-mods/flib/files/4661080
