### ISSUE TITLE
CTD with Cyclic

### ISSUE THREAD

**Issue by Rightfuldeathray** [Lothrazar/FLib#4]
Minecraft Version: 1.20.1

Forge Version: 47.2.32

FLIB Mod Version: 0.0.13
Cyclic Mod Version: 1.12.9

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

Latest version of FLIB with Cyclic causes immediate CTD upon joining the world

ReportedException: Ticking player
NoSuchFieldError: STEP_HEIGHT

Use of Neruina (Ticking Entity Fixer) causes the player to be kicked instead of a crash

FLIB Mod Version: 0.0.12 does not cause a crash

Log file link:
[https://pastebin.com/2Er8kJnj](https://pastebin.com/2Er8kJnj)

**Comment by SeagalKru** [comment]
Hello.
After updating your mod from version 1.20.1 - 0.0.12 to version 1.20.1 - 0.0.13, I was no longer allowed to join the server.
I attach files from the server and client below:
from the server:
[debug.log](https://github.com/Lothrazar/FLib/files/15377027/debug.log)
[latest.log](https://github.com/Lothrazar/FLib/files/15377028/latest.log)

from the client:
[latest.log](https://github.com/Lothrazar/FLib/files/15377030/latest.log)

Thank you

**Comment by Rightfuldeathray** [comment]
This issue is most talked about under [Cyclic #2410](https://github.com/Lothrazar/Cyclic/issues/2410)
For more information/logs/repeatability check there

**Comment by muggleorwizard** [comment]
Same issue with my modpack, I was unable to update flib without causing crashes.

**Comment by raziel23x** [comment]
same

**Comment by Lothrazar** [comment]
Update to the latest versions of everything to get the fix. Specifically

Neoforge 47.1.99+

OR
‌

(old)forge 47.1.47+
and

cyclic 1.20.1-1.12.9

flib 0.0.14

**Comment by Lothrazar** [comment]
Fixed compatibility with old-forge as of https://www.curseforge.com/minecraft/mc-mods/flib/files/5495793
